### ISSUE TITLE
setup-ros-workspace is a bit confusing

### ISSUE THREAD

**Issue by mamueluth** [StoglRobotics/ros_team_workspace#58]
If executing `setup-ros-workspace ROS_DISTRO WS_FOLDER WS_PREFIX WS_SUFFIX` one might think that a new ros-workspace with the name `WS_FOLDER` is created. but instead a workspace called `<WS_PREFIX>_<ROS_DISTRO>_<WS_SUFFIX>` is created inside the `WS_FOLDER`. This might be over complicated and confusing.

Suggested change with introduction of CLI would be to simplify from:

> `setup-ros-workspace ROS_DISTRO WS_FOLDER WS_PREFIX WS_SUFFIX`

to 

> `setup-ros-workspace WS_FOLDER ROS_DISTRO

and create a workspace called `WS_FOLDER` inside current `$pwd` or if path like `~/` or `/home/<user>/` is given, then relative to `$HOME`

**Comment by destogl** [comment]
ROS distro in workspace name was shown very useful during use since usually, one has multiple version setup in parallel. Prefixes and suffixes are also very, very useful when one is using multiple versions and multiple development stages.

Can we add both cases. You case as default and other parameters would be added with flags.

**Comment by mamueluth** [comment]
Done with #53
